spring.application.name=AyurMatters
server.port=8080

#spring.datasource.url=jdbc:h2:mem:ayurmatters
#spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=never

spring.datasource.url=jdbc:postgresql://dpg-d623rlsr85hc73dcng6g-a:5432/ayurmatters_db
spring.datasource.username=ayurmatters_db_user
spring.datasource.password=ufhg1FtuvqxvUGBLNDS8QRi7DsuQWJdV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



